few_shots = [
    {'Question' : "tell me sell of date 2021-01-03 ?",
     'SQLQuery' : "SELECT sum(Total) FROM chinook.invoice where InvoiceDate = '2021-01-03 00:00:00' ;",
     'SQLResult': "Result of the SQL query",
     'Answer' : "5.94"},
     {'Question' : "tell me the name of all the tracks that was bought on 1st of march 2021 ?",
     'SQLQuery' : "SELECT t.Name FROM track t JOIN invoiceline il ON t.TrackId = il.TrackId JOIN invoice i ON i.InvoiceId = il.InvoiceId WHERE i.InvoiceDate = '2021-01-03 00:00:00';",
     'SQLResult': "Result of the SQL query",
     'Answer' : "Dog Eat Dog, Overdose, Love In An Elevator, Janie's Got A Gun, Deuces Are Wild, Angel"},
     {'Question' : "tell me post of Robert ?",
     'SQLQuery' : "SELECT Title FROM chinook.employee WHERE FirstName = 'Robert';",
     'SQLResult': "Result of the SQL query",
     'Answer' : "IT Staff"},
     {'Question' : "tell me Title of Robert ?",
     'SQLQuery' : "SELECT Title FROM chinook.employee WHERE FirstName = 'Robert';",
     'SQLResult': "Result of the SQL query",
     'Answer' : "IT Staff"},
     {'Question' : "tell me post of Michael ?",
     'SQLQuery' : "SELECT Title FROM chinook.employee WHERE FirstName = 'Michael';",
     'SQLResult': "Result of the SQL query",
     'Answer' : "IT Manager"},
     {'Question' : "tell me Title of my employee Mitchell ?",
     'SQLQuery' : "SELECT Title FROM chinook.employee WHERE FirstName = 'Mitchell';",
     'SQLResult': "Result of the SQL query",
     'Answer' : "No data found"},
]

